### ISSUE TITLE
Question 5 is not searching for exact account

### ISSUE THREAD

**Issue by dcfreema** [dcfreema/CSE233#1]
123 will give a positive result comparing to 1234567.

**Comment by JacquesTheRock** [comment]
Just do the following(Update the messages to your original style): 
f = open("text5.txt",'r')
acc = input("Please input an account")
if acc in f:
	print("Account found")
else:
print("Account not found")

**Comment by dcfreema** [comment]
@JacquesTheRock  fixed in #08495a7
